# Change these first
owner: stokedconsulting # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Desirable Web App
    url: https://desirable.app
    icon: https://desirable.app/favicon.ico
  - name: API Service
    url: https://api.desirable.app/v3.0/health
  - name: WebRTC Service
    url: https://webrtc.desirable.app/health
  - name: Chat Service
    url: https://chat.desirable.app/chat/health

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.desirable.app
  # baseUrl: /status
  logoUrl: https://desirable.app/logo.png
  name: Desirable Status
  introTitle: "**Desirable** System Status"
  introMessage: Real-time service status for the Desirable v3.0 platform.
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://desirable.app
    - title: Support
      href: mailto:support@desirable.app

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
